persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Listener for MQTT TCP
listener 1883
protocol mqtt
allow_anonymous true

# Listener for MQTT-WebSocket (used by browser-based UIs)
listener 9001
protocol websockets
allow_anonymous true

# Performance
max_connections -1
max_inflight_bytes 0
max_queued_messages 10000
queue_qos0_messages false

# Keepalive
keepalive_interval 60
